package cbom.eccg.symmetric_atomic_primitives.constants 

MINIMUM_RECOMMENDED_BITS_FOR_QUANTUM_SENSITIVE_CONTEXT_BLOCK_CIPHER := 192
MINIMUM_RECOMMENDED_BITS_FOR_QUANTUM_SENSITIVE_CONTEXT_HASH := 384

TRIPLE_DES_REQUIRED_KEY_BITS := 168
TRIPLE_DES_LEGACY_MARKER := "L[2027]"

AGREED_BLOCK_CIPHER_ALGORITHM_NAMES := {
    "AES",
}

AES_ALLOWED_KEY_SIZES := {128, 192, 256}

AGREED_HASH_ALGORITHM_NAMES := {
    "SHA-256",
    "SHA-384",
    "SHA-512",
    "SHA-512/256",
    "SHA3-256",
    "SHA3-384",
    "SHA3-512",
}
